### PR TITLE
TableView: optimizing continuous numbering

### PR DESCRIPTION
**Pull request by Rackar**
of revision in mock

### CODE REVIEW

**Comment by JohannesLichtenberger** [comment]
Thank you :-)

**Comment by JohannesLichtenberger** [comment]
BTW: you think we can switch here to TypeScript, too?

**Comment by Rackar** [comment]
I'm too bad in TS to code anything. Maybe later.

**Comment by JohannesLichtenberger** [comment]
No worries, maybe someone can help :-) I think as the project grows it might be better to use TypeScript.

But that said we can still rewrite it and your work is invaluable +1

**Pull request merged**
