### PR TITLE
query component. Get one JSON data,  and change it to 3 views.

### PR DESCRIPTION
**Pull request by Rackar**
change dev port 3000 to 3005.

### CODE REVIEW

**Comment by JohannesLichtenberger** [comment]
Hi Rackar, thanks so much for all your work. We have a serious issue with Nuxt.js, TypeScript and Element-UI:

https://github.com/sirixdb/sirix-web-frontend/issues/18

Do you know if we can make a workaround here to fix this directly in the repository such that our Github Action doesn't fail? A strange thing is also that the Element-UI repository hasn't been updated since 24 days.

**Comment by JohannesLichtenberger** [comment]
Hey, currently I'm getting an error:

` ERROR  ERROR in /home/johannes/sirix-web-frontend/pages/query/index.vue(91,9):    nuxt:typescript 08:49:18
91:9 Type 'any[]' is not assignable to type 'never[]'.
  Type 'any' is not assignable to type 'never'.
    89 |           data: json
    90 |         };
  > 91 |         this.data = this.formatTree(data);
       |         ^
    92 | 
    93 |         this.XML = this.formatXML(data);
    94 |       });
`

**Comment by pareshjoshi** [comment]
@JohannesLichtenberger every new change is breaking the functionality.

@Rackar - does this work for you locally?

**Comment by Rackar** [comment]
Is there any problem yet? Nuxt.js has already defined a loading component, I think we can just change the link to fix. I can't see the error message now.

**Comment by Rackar** [comment]
> Hi Rackar, thanks so much for all your work. We have a serious issue with Nuxt.js, TypeScript and Element-UI:
> 
> #18
> 
> Do you know if we can make a workaround here to fix this directly in the repository such that our Github Action doesn't fail? A strange thing is also that the Element-UI repository hasn't been updated since 24 days.

Action failed because there is no test script. Element is wonderful. Many small problem caused by TS and Nuxt.js.

**Pull request merged**
