### PR TITLE
Setup Dependency Injection

### PR DESCRIPTION
**Pull request by jawahars16**
Instead of having the data fetching logic directly in the component, it is always better to move that logic to service class and pass it through dependency injection. Following changes were made in this commit.

- Created dependency container to register dependencies.
- Loading the container from main.ts
- Created data service to fetch history data.
- Injected data service into table component.
- Extracted models into separate folder

### CODE REVIEW

**Comment by JohannesLichtenberger** [comment]
What do you think? Should we move to Nuxt.js?

**Comment by jawahars16** [comment]
Yes Nuxt.js would be a good option. 👍

**Comment by JohannesLichtenberger** [comment]
Already switched thanks to another contribution :-)

**Comment by JohannesLichtenberger** [comment]
@all-contributors please add @jawahars16 for code

**Pull request merged**
